---
provisioner:
  name: terraform

platforms:
  - name: terraform

suites:
  - name: gcp-log-export
    driver:
      name: terraform
      root_module_directory: examples/gcp-log-export
      parallelism: 2
      command_timeout: 1800
    verifier:
      name: terraform
      systems:
        - name: inspec-gcp
          backend: gcp
  - name: sumologic-gcp-source
    driver:
      name: terraform
      root_module_directory: examples/sumologic-gcp-source
      parallelism: 2
      command_timeout: 1800
    verifier:
      name: terraform
      systems:
        - name: basic
          backend: local
