---
provisioner:
  name: terraform

verifier:
  name: terraform
  systems:
    - name: echo
      backend: local

platforms:
  - name: terraform

suites:
  - name: simple-template
    driver:
      name: terraform
      root_module_directory: examples/simple-template
      parallelism: 1
      command_timeout: 1800
